### ISSUE TITLE
Why is TBXImageList is not a part of TBX

### ISSUE THREAD

**Issue by zedxxx** [plashenkov/TBX#15]
We use old version of TBX 2.2 alpha (with some fixes) which was include design-time component TTBXImageList. I wanted to start using your version of TBX but I found that this component is missing.

So, I want to ask you why is it missing and is it possible to include it?

TBX 2.2 alpha: https://torry.net/files/vcl/bars/toolbars/tbx22alpha.zip

TBXImageList is 4 units:
- Design\TBXImgListEdit.pas
- TBXGraphics.pas                       <-- class TTBXImageList is here
- TBXGraphicsPNG.pas
- TBXGraphicsZLIB.pas

This component still works for Delphi 2007 to latest Rio 10.3.2 (for Win32 target only).

[TBXImageList_Rio.zip](https://github.com/plashenkov/TBX/files/3888808/TBXImageList_Rio.zip) (with some minor fixes for Rio).

**Comment by plashenkov** [comment]
Hi zedxxx!

As far as I remember, TBX 2.2-alpha was a special version of TBX, it was Unicode-enabled while even Delphi did not support Unicode directly. It played well with the special third-party Unicode component suite (I do not remember its name already) — which contained all standard controls but Unicode-enabled.

Since then Delphi got its own native Unicode support. Version 2.2-alpha of TBX did not get wide use, as far as I know. Many improvements by third-party developers were made exactly into TBX 2.1 version, which became Unicode-enabled automatically after Delphi got Unicode natively.

This version of TBX derives from the original TBX 2.1, this is why it misses TBXImageList — there was no TBXImageList in TBX 2.1.

**Comment by plashenkov** [comment]
Yup, just for information: Unicode component suite was Tnt Unicode Controls from TntWare. Later they turned into commercial after TMS software purchased them: https://www.tntware.com/delphicontrols/unicode/.

Regarding image list... If you want to make a transition to this version of TBX, you can try to add TBXImageList manually; or maybe use another image list solution, for example, PngImageList — https://cc.embarcadero.com/Item/26127

**Comment by zedxxx** [comment]
Ok, thank you for the explanation. 

So, how about backport TBXImageList from TBX 2.2 into 2.1? As I can see, it can be done very easy.

**Comment by zedxxx** [comment]
Look at this: TBXImageList compatible with your versions of TBX and Toolbar2000: [TBXImageList.zip](https://github.com/plashenkov/TBX/files/3892385/TBXImageList.zip) 

Tested with Delphi 10.3.3 (Win32 and Win64).

Take attention to the `TCustomImageListCrack` (TBXGraphics.pas) - I don't know exactly in which Delphi version declaration of `TCustomImageList` changed.

**Comment by plashenkov** [comment]
I do not know when I will be able to do that. If possible, create a PR.

**Comment by zedxxx** [comment]
https://github.com/plashenkov/TBX/pull/16

**Comment by plashenkov** [comment]
Merged. Thank you!
